### ISSUE TITLE
Thumbnail via path / No database require

### ISSUE THREAD

**Issue by X17** [ninapavlich/django-imagekit-cropper#8]
Is it possible to achieve cropping without saving the cropped image to database , as we can restore it via path.

let's say image abc.jpg created thumb with prefix thumb_1_abc.jpg. we can anyways get the image when we put path in place.

PS: how can we set prefix to thumbnails?

**Comment by ninapavlich** [comment]
Hi @X17! I'm so sorry, I was out of town when your issue came through and I just saw it now.

The cropped image itself doesn't get stored in the database; only the image and the crop values get stored. Can you post a snippet of your imagekit code so I can understand a little better what you're trying to achieve?

In terms of setting the prefix for thumbnails, the filenames are generated in imagekit, so I would take a look at their documentation. Specifically, the IMAGEKIT_CACHEFILE_NAMER setting might be what you're looking for.

**Comment by ninapavlich** [comment]
Hi @X17,

I'm going to close since I haven't heard back.
